import { streamText, generateText } from "ai"
import { openai } from "@ai-sdk/openai"

export async function POST(req: Request) {
  try {
    const { prompt } = await req.json()

    if (!prompt) {
      return new Response("Missing prompt", { status: 400 })
    }

    const productContext = `Product Information:\n${prompt}`

    // 1. Parallel Workers Phase
    // Spawn 6 workers to generate deep insights into specific architectural domains
    const [
      backendReport,
      databaseReport,
      aiInfraReport,
      devopsReport,
      securityReport,
      costReport
    ] = await Promise.all([
      // Backend Worker
      generateText({
        model: openai("gpt-4o-mini"),
        system: "You are an expert Backend Architect. Design the API Gateway, microservices/monolith structure, authentication, and core services. Focus on zero-cost, open-source solutions.",
        prompt: productContext,
      }),
      // Database Worker
      generateText({
        model: openai("gpt-4o-mini"),
        system: "You are an expert Database Architect. Design the SQL/NoSQL schemas, vector databases for AI, relationships, and caching strategy using free/open-source tools.",
        prompt: productContext,
      }),
      // AI Infra Worker
      generateText({
        model: openai("gpt-4o-mini"),
        system: "You are an AI Systems Architect. Design the local/self-hosted AI infrastructure using Ollama, vLLM, or llama.cpp. Detail the RAG pipeline, embeddings, and prompt routing. NO paid APIs.",
        prompt: productContext,
      }),
      // DevOps Worker
      generateText({
        model: openai("gpt-4o-mini"),
        system: "You are a DevOps Architect. Design the CI/CD pipeline, Docker/Kubernetes deployment strategy, monitoring, and scaling path from 0 to 1M users using self-hosted tools.",
        prompt: productContext,
      }),
      // Security Worker
      generateText({
        model: openai("gpt-4o-mini"),
        system: "You are a Security Architect. Design the RBAC, OAuth, rate limiting, secrets management, and AI safety layer (prompt injection mitigation).",
        prompt: productContext,
      }),
      // Cost & Scaling Worker
      generateText({
        model: openai("gpt-4o-mini"),
        system: "You are a Cloud & Cost Optimization Architect. Estimate the hardware requirements and costs for MVP up to 1M users. Emphasize how to keep costs as close to zero as possible.",
        prompt: productContext,
      })
    ])

    // 2. Merger Phase
    // Combine all worker reports into a massive context block
    const mergedContext = `
--- BACKEND EXPERT REPORT ---
${backendReport.text}

--- DATABASE EXPERT REPORT ---
${databaseReport.text}

--- AI INFRASTRUCTURE EXPERT REPORT ---
${aiInfraReport.text}

--- DEVOPS & SCALING EXPERT REPORT ---
${devopsReport.text}

--- SECURITY EXPERT REPORT ---
${securityReport.text}

--- COST ANALYSIS EXPERT REPORT ---
${costReport.text}
    `

    const leadArchitectPrompt = `
You are the Lead Technical Architect. You have assigned several expert engineers to draft the architecture for this product idea. 
Below are their detailed reports.

Your job is to merge their insights into a single, cohesive, highly professional Engineering Blueprint Document.
Format it in beautiful Markdown.
Include a Table of Contents at the beginning.
Include at least two Mermaid diagrams (e.g., one for High-Level Architecture, one for AI Request Flow).
Do NOT mention that this was generated by multiple experts—present it as a unified master plan.
Focus heavily on the "Zero API Cost" and self-hosted constraints.

### Expert Reports:
${mergedContext}
`

    // 3. Final Stream
    // The Lead Architect generates the final document and streams it to the client
    const result = streamText({
      model: openai("gpt-4o"), // Use the smartest model for the final assembly
      system: leadArchitectPrompt,
      prompt: "Generate the final Architecture Document now.",
    })

    return result.toTextStreamResponse()
  } catch (error) {
    console.error("Multi-Agent Architecture Error:", error)
    return new Response("Internal Server Error", { status: 500 })
  }
}
