"""
Seed data for 16 Indian cities with realistic regional indices.
"""

from app.models.city import City


CITIES = [
    {
        "name": "Mumbai",
        "state": "Maharashtra",
        "pin_code_prefix": "400",
        "construction_index": 1.18,
        "labour_index": 1.24,
        "material_index": 1.15,
        "approval_index": 1.18,
        "inflation_index": 1.10,
        "transportation_index": 1.20,
        "availability_index": 0.95,
        "base_rate_economy": 1800,
        "base_rate_standard": 2400,
        "base_rate_premium": 3400,
        "base_rate_luxury": 4800,
        "base_rate_ultra_luxury": 7500,
    },
    {
        "name": "Delhi NCR",
        "state": "Delhi",
        "pin_code_prefix": "110",
        "construction_index": 1.08,
        "labour_index": 1.12,
        "material_index": 1.08,
        "approval_index": 1.10,
        "inflation_index": 1.08,
        "transportation_index": 1.05,
        "availability_index": 0.98,
        "base_rate_economy": 1600,
        "base_rate_standard": 2200,
        "base_rate_premium": 3100,
        "base_rate_luxury": 4300,
        "base_rate_ultra_luxury": 6800,
    },
    {
        "name": "Gurgaon",
        "state": "Haryana",
        "pin_code_prefix": "122",
        "construction_index": 1.10,
        "labour_index": 1.15,
        "material_index": 1.10,
        "approval_index": 1.08,
        "inflation_index": 1.08,
        "transportation_index": 1.06,
        "availability_index": 0.97,
        "base_rate_economy": 1650,
        "base_rate_standard": 2000,
        "base_rate_premium": 2700,
        "base_rate_luxury": 3800,
        "base_rate_ultra_luxury": 6000,
    },
    {
        "name": "Bangalore",
        "state": "Karnataka",
        "pin_code_prefix": "560",
        "construction_index": 1.06,
        "labour_index": 1.08,
        "material_index": 1.10,
        "approval_index": 1.05,
        "inflation_index": 1.06,
        "transportation_index": 1.08,
        "availability_index": 0.96,
        "base_rate_economy": 1600,
        "base_rate_standard": 2100,
        "base_rate_premium": 2800,
        "base_rate_luxury": 4000,
        "base_rate_ultra_luxury": 6500,
    },
    {
        "name": "Hyderabad",
        "state": "Telangana",
        "pin_code_prefix": "500",
        "construction_index": 0.96,
        "labour_index": 0.92,
        "material_index": 0.96,
        "approval_index": 0.95,
        "inflation_index": 1.04,
        "transportation_index": 0.98,
        "availability_index": 1.02,
        "base_rate_economy": 1400,
        "base_rate_standard": 1900,
        "base_rate_premium": 2600,
        "base_rate_luxury": 3700,
        "base_rate_ultra_luxury": 5800,
    },
    {
        "name": "Pune",
        "state": "Maharashtra",
        "pin_code_prefix": "411",
        "construction_index": 1.02,
        "labour_index": 1.02,
        "material_index": 1.05,
        "approval_index": 1.00,
        "inflation_index": 1.05,
        "transportation_index": 1.02,
        "availability_index": 1.00,
        "base_rate_economy": 1500,
        "base_rate_standard": 2000,
        "base_rate_premium": 2700,
        "base_rate_luxury": 3800,
        "base_rate_ultra_luxury": 6000,
    },
    {
        "name": "Chennai",
        "state": "Tamil Nadu",
        "pin_code_prefix": "600",
        "construction_index": 1.00,
        "labour_index": 0.98,
        "material_index": 1.02,
        "approval_index": 1.02,
        "inflation_index": 1.05,
        "transportation_index": 1.05,
        "availability_index": 0.98,
        "base_rate_economy": 1500,
        "base_rate_standard": 1950,
        "base_rate_premium": 2650,
        "base_rate_luxury": 3700,
        "base_rate_ultra_luxury": 5800,
    },
    {
        "name": "Ahmedabad",
        "state": "Gujarat",
        "pin_code_prefix": "380",
        "construction_index": 0.92,
        "labour_index": 0.88,
        "material_index": 0.92,
        "approval_index": 0.90,
        "inflation_index": 1.03,
        "transportation_index": 0.95,
        "availability_index": 1.05,
        "base_rate_economy": 1300,
        "base_rate_standard": 1750,
        "base_rate_premium": 2400,
        "base_rate_luxury": 3400,
        "base_rate_ultra_luxury": 5200,
    },
    {
        "name": "Kolkata",
        "state": "West Bengal",
        "pin_code_prefix": "700",
        "construction_index": 0.90,
        "labour_index": 0.85,
        "material_index": 0.90,
        "approval_index": 0.95,
        "inflation_index": 1.04,
        "transportation_index": 1.00,
        "availability_index": 1.00,
        "base_rate_economy": 1250,
        "base_rate_standard": 1700,
        "base_rate_premium": 2350,
        "base_rate_luxury": 3300,
        "base_rate_ultra_luxury": 5000,
    },
    {
        "name": "Jaipur",
        "state": "Rajasthan",
        "pin_code_prefix": "302",
        "construction_index": 0.88,
        "labour_index": 0.82,
        "material_index": 0.88,
        "approval_index": 0.85,
        "inflation_index": 1.02,
        "transportation_index": 0.92,
        "availability_index": 1.05,
        "base_rate_economy": 1200,
        "base_rate_standard": 1650,
        "base_rate_premium": 2300,
        "base_rate_luxury": 3200,
        "base_rate_ultra_luxury": 4800,
    },
    {
        "name": "Lucknow",
        "state": "Uttar Pradesh",
        "pin_code_prefix": "226",
        "construction_index": 0.85,
        "labour_index": 0.78,
        "material_index": 0.85,
        "approval_index": 0.82,
        "inflation_index": 1.02,
        "transportation_index": 0.90,
        "availability_index": 1.08,
        "base_rate_economy": 1150,
        "base_rate_standard": 1550,
        "base_rate_premium": 2150,
        "base_rate_luxury": 3000,
        "base_rate_ultra_luxury": 4500,
    },
    {
        "name": "Chandigarh",
        "state": "Chandigarh",
        "pin_code_prefix": "160",
        "construction_index": 0.95,
        "labour_index": 0.95,
        "material_index": 0.98,
        "approval_index": 0.92,
        "inflation_index": 1.04,
        "transportation_index": 0.95,
        "availability_index": 1.02,
        "base_rate_economy": 1400,
        "base_rate_standard": 1850,
        "base_rate_premium": 2500,
        "base_rate_luxury": 3500,
        "base_rate_ultra_luxury": 5500,
    },
    {
        "name": "Kochi",
        "state": "Kerala",
        "pin_code_prefix": "682",
        "construction_index": 0.92,
        "labour_index": 0.90,
        "material_index": 0.95,
        "approval_index": 0.88,
        "inflation_index": 1.03,
        "transportation_index": 1.02,
        "availability_index": 1.00,
        "base_rate_economy": 1350,
        "base_rate_standard": 1800,
        "base_rate_premium": 2500,
        "base_rate_luxury": 3500,
        "base_rate_ultra_luxury": 5500,
    },
    {
        "name": "Indore",
        "state": "Madhya Pradesh",
        "pin_code_prefix": "452",
        "construction_index": 0.82,
        "labour_index": 0.75,
        "material_index": 0.82,
        "approval_index": 0.80,
        "inflation_index": 1.01,
        "transportation_index": 0.88,
        "availability_index": 1.10,
        "base_rate_economy": 1100,
        "base_rate_standard": 1450,
        "base_rate_premium": 2000,
        "base_rate_luxury": 2800,
        "base_rate_ultra_luxury": 4200,
    },
    {
        "name": "Goa",
        "state": "Goa",
        "pin_code_prefix": "403",
        "construction_index": 1.02,
        "labour_index": 0.95,
        "material_index": 1.05,
        "approval_index": 1.10,
        "inflation_index": 1.06,
        "transportation_index": 1.15,
        "availability_index": 0.90,
        "base_rate_economy": 1550,
        "base_rate_standard": 2050,
        "base_rate_premium": 2800,
        "base_rate_luxury": 4000,
        "base_rate_ultra_luxury": 6500,
    },
    {
        "name": "Nagpur",
        "state": "Maharashtra",
        "pin_code_prefix": "440",
        "construction_index": 0.85,
        "labour_index": 0.78,
        "material_index": 0.85,
        "approval_index": 0.82,
        "inflation_index": 1.02,
        "transportation_index": 0.90,
        "availability_index": 1.05,
        "base_rate_economy": 1150,
        "base_rate_standard": 1550,
        "base_rate_premium": 2150,
        "base_rate_luxury": 3000,
        "base_rate_ultra_luxury": 4500,
    },
]


async def seed_cities() -> int:
    """Insert all cities into the database. Returns count of inserted cities."""
    count = 0
    for city_data in CITIES:
        existing = await City.filter(name=city_data["name"]).first()
        if not existing:
            await City.create(**city_data)  # type: ignore
            count += 1

    return count
